# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TfImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='tf_images')),
                ('result', models.TextField(blank=True, default='', null=True)),
                ('upload_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
