# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TfImages',
            new_name='TfImage',
        ),
    ]
